### ISSUE TITLE
Flexibilizar validación (2): una distribución con "pocas" series nulas no debe fallar

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar#10]
Siguiendo al issue #458, deberíamos modificar la validación de series nulas (aquellas que no tienen por lo menos 2 valores) para que sólo haga fallar una distribución que supere un umbral porcentual (0.05) de series de la distribución que son series nulas.

**Comment by lucaslavandeira** [comment]
Resuelto en 0.2.0
