### ISSUE TITLE
Validaciones del índice de tiempo

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/series-tiempo-ar#2]
Ver [este issue](https://github.com/datosgobar/series-tiempo-ar-api/issues/8)

**Metadatos**: aquellas que sean necesarias para asegurar la integridad de las funcionalidades de la API (hay un conjunto de campos de metadatos que deben estar OK para que la API pueda funcionar con esas series, otros no)

**Datos**: aquellas que dependen de descargarse la distribución y _hacer algo con ella_. Algunas validaciones sólo se hacen sobre la distribución, otras validan la consistencia entre la distribución y los metadatos.

**Ejemplos del ETL de Series de Tiempo**

En el método [`validate_distribution`](https://github.com/datosgobar/series-tiempo/blob/master/scripts/validation.py#L189) del módulo `validations.py` del ETL de series de tiempo se listan un conjunto de validaciones que toda distribución debe pasar, excepto: `TimeIndexFutureTimeValueError` (puede haber series que sean proyecciones futuras, eliminaría esta validación de la lista).

Dudo que el código sea re-utilizable, pero termina siendo (creo) una buena lista de las validaciones que hoy entiendo que hay que hacer.

**Índices de tiempo "sanos": asegurados por el scraper `xlseries`**

Las que no están incluidas en `validation.py`, son muchas de las que surgen automáticamente de `xlseries` (un scraper) que donde no cuadra con alguna de las frecuencias que soporta lanza una Exception y se olvida.

Acá hay que diseñar validaciones para asegurar índices de tiempo "sanos" (al menos para el modelo actual de extracción de datos que nos planteamos, en el futuro puede haber uno o más modelos diferentes):

- [ ] Las fechas están _siempre_ en ISO 8601 (`YYYY-MM-DD`)
- [x] Las fechas van siempre en orden ascendente (primera fila tiene el valor más antiguo, última fila el más reciente).
- [x] Las fechas pueden tener la parte de "tiempo" luego de la de "fecha", pero se desestima. (`YYYY-MM-DD` es exactamente igual que `YYYY-MM-DDThh:mm:ss`.
- [x] Para una frecuencia dada (anual, semestral, trimestral, mensual o diaria) las fechas admiten usar sólo la parte del estándar de fecha necesaria o usar la forma de fecha completa
    + Anual: YYYY está ok
    + Anual: YYYY-MM-DD está ok
    + Mensual: YYYY-MM está ok
    + Mensual: YYYY NO está ok
    + Trimestral: YYYY-MM está ok
    + Trimestral: YYYY NO está ok
- [x] Las fechas están completas (el índice de tiempo es _continuo_).
    + Anual: 1980 / 1981 / 1982 está ok
    + Anual: 1980 / 1982 / 1983 NO está ok
    + Diaria: admitir acá 2 casos: frecuencia diaria _completa_ (lunes a domingo) y frecuencia diaria _hábil_ o `Business Daily` (lunes a viernes). Pero no puede nunca faltar un "martes", ni puede haber algunos sábados pero otros no.

**Casos más avanzados para abordar en el futuro**

- [x] Para una frecuencia dada (anual, semestral, trimestral, mensual o diaria) donde se use la forma completa, se admite tanto usar _la fecha inicial_ como _la fecha final_ del período, pero no una mezcla entre ambas (o una, o la otra) y los datos se guardan y devuelven en la API tal como los puso el usuario. (*ITERABLE: podemos arrancar limitándonos a soportar _fecha inicial_ ie. "01" y abordar mucho más adelante el otro caso. Para esto pondría una validación que busque siempre completar con _fecha inicial_ del período "01" para las partes de la fecha que sobran*)
    + Mensual: 1980-01-01 / 1980-02-01 / 1980-03-01 está ok
    + Mensual: 1980-01-31 / 1980-02-28 / 1980-03-31 está ok
    + Mensual: 1980-01-31 / 1980-02-28 / 1980-03-31 está ok
    + Mensual: 1980-01-31 / 1980-02-01 / 1980-03-31 NO está ok
- [x] Para una frecuencia dada (relevante para anual, semestral o trimestral, sobre todo) donde se use la forma completa, *siempre se debe respetar la distancia entre períodos* (hay 12 meses entre fecha y fecha de una anual, hay 6 meses entre fecha y fecha de una semestral y hay 3 meses entre fecha y fecha de una trimestral) pero estos pueden empezar *en distintos momentos del año*.
 (*ITERABLE: podemos arrancar limitándonos a soportar los momentos "canónicos" que son: los años empiezan siempre en enero, los semestren en enero-julio y los trimestres en enero-abril-julio-octubre; y abordar mucho más adelante el otro caso. Para esto pondría una validación que busque siempre estos comienzos dependiendo de la frecuencia*)
    + Semestral: 1980-01-01 / 1980-07-01 / 1981-01-01 está ok
    + Semestral: 1980-03-01 / 1980-09-01 / 1981-03-01 está ok
    + Semestral: 1980-04-01 / 1980-09-01 / 1981-04-01 NO está ok

**Comment by abenassi** [comment]
Este issue quedo extemporáneo y la mayoría de las validaciones están implementadas.
